Starting to implement song query search
Currently, when it comes to the song similarity search process, searching by Spotify track URL, track ID, and ISRC are supported, but several other forms of search have yet to be implemented; most notably, searching by song query. The user may want to type in a song name (eg. Mr. Brightside) and have Spaudible pull up the corresponding track ID by querying the local Spotify database. This commit is a launchpad for this new search feature. While it's not fully implemented yet and remains buggy, I think we're not too far from it producing viable results.

A song query may take the form of:

song
song artist
artist song
song album
album song

and potentially other variations I have yet to decide upon. Ideally, it should find the best match, sorted by accuracy and popularity.

As of now, it's incredibly slow, and errors out at the end of a search:

Error: 'FormattedTextControl' object has no attribute 'window'

I assume this is tied to the newly-added required package "prompt_toolkit", which handles an interactive, more user-friendly CLI menu.

Fuzzy search is on the table, but first, I need to make sure the baseline search querying works optimally.